version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"  # Exposes MongoDB on localhost:27017
    environment:
      MONGO_INITDB_DATABASE: userdb
      # Uncomment and set these if you want to enable authentication
      # MONGO_INITDB_ROOT_USERNAME: admin
      # MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"  # Exposes Mongo Express on localhost:8081
    environment:
      # Uncomment and set these if using MongoDB authentication
      # ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      # ME_CONFIG_MONGODB_ADMINPASSWORD: adminpassword
      ME_CONFIG_MONGODB_URL: "mongodb://mongodb:27017/userdb"
    depends_on:
      - mongodb

volumes:
  mongo-data:
